# Generated by Django 5.0 on 2023-12-17 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
