# Generated by Django 5.0 on 2023-12-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orderreport_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
