# Generated by Django 5.0 on 2023-12-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orderreport_order_alter_orderitems_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderreport',
            old_name='order',
            new_name='order_id',
        ),
    ]
