# Generated by Django 5.0 on 2023-12-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_orderreport_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreport',
            name='order_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_report', to='main.orders'),
        ),
    ]
