# Generated by Django 5.0 on 2023-12-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_orderreport_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreport',
            name='order_id',
        ),
    ]
