# Generated by Django 5.0 on 2023-12-18 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_orderitems_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreport',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
